### ISSUE TITLE
Security Checklist

### ISSUE THREAD

**Issue by SommerEngineering** [SommerEngineering/KPIManager#8]
- [x] The web handler for showing the results must be bound to the public server
- [x] The web handler for adding values to a channel must be bound to the admin server
- [x] The web handler for adding values must use a password. Each channel can use another password.
- [x] The admin control is secured by a password. In order to do so, a change in the project Ocean is maybe necessary.
